### PR TITLE
Create harbour-podcatcher-sv.ts

### PR DESCRIPTION
**Pull request by eson57**
Hi,

I like this app so I created Swedish translation. Found some missing/not working strings to...

skarmbild_20160902_002

### CODE REVIEW

**Comment by CarolusMagnus** [comment]
Thank you very much.  Hopefully I found now all untranslated strings. Maybe you can translate them also.

**Comment by eson57** [comment]
Of course I will. Please ping me, when there are new strings to translate. I'm almost always on keyboard.

**Comment by CarolusMagnus** [comment]
The updated ts-file is now here on GitHub.

**Comment by eson57** [comment]
Thanks, I missed it with just a few seconds.  :-)

**Comment by CarolusMagnus** [comment]
I found other strings, which were not yet prepared for translation. Maybe you want to the Swedish localization for them.

**Pull request merged**
